name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'   # change to your required Node version
          cache: 'pnpm'

      # 3. Install pnpm globally
      - name: Install pnpm
        run: npm install -g pnpm

      # 4. Cache pnpm store for faster installs
      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # 5. Install dependencies
      - name: Install dependencies
        run: pnpm install

      # 6. Build the Next.js project
      - name: Build
        run: pnpm build

      # 7. Optional: Run tests if you have any
      - name: Run tests
        run: pnpm test

      # 8. Optional: Output pnpm version
      - name: Check pnpm version
        run: pnpm --version
